[package]
name = "chefi"
version = "0.1.0"
authors = ["Cole Mickens <cole.mickens@gmail.com>"]

[dependencies]
clap = "^2.19"
error-chain = "^0.7"
futures = "^0.1"
iron = "^0.4"
log = "^0.3"
mount = "^0.2"
rand = "^0.3"
slog = "^1.4"
slog-json = "^1.2"
slog-stream = "^1.2"
slog-term = "^1.3"
staticfile = "^0.3"
tokio = "^0.0"
tokio-core = "^0.1"
tokio-proto = { git = "https://github.com/tokio-rs/tokio-proto" }
